In [ ]:
- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. 
Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [48]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

def resum_estadistic(a):
    
     if a.ndim > 1:
        print('Error: The array must be 1-D')
    
     else:
        print('minimum:', np.amin(a))
        print('maximum:', np.amax(a))
        print('range of values:', np.ptp(a))
        print('median:', np.median(a))
        print('weighted average:',np.average(a))
        print('arithmetic mean:',np.mean(a))
        print('standard deviation:',np.std(a))
        print('variance:',np.var(a))

    
resum_estadistic(arr)
   
    

minimum: 1
maximum: 10
range of values: 9
median: 5.5
weighted average: 5.5
arithmetic mean: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [ ]:
- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [85]:

import numpy as np
from numpy.random import seed
from numpy.random import randint

def quadrat_random():
    n = int(input())
    seed(1)
    quadrat = np.random.randint(0,100,size = (n,n))
    
    print(quadrat)
    
    
quadrat_random()
    

3
[[37 12 72]
 [ 9 75  5]
 [79 64 16]]


In [ ]:
- Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [79]:
import numpy as np

#Creem una matriu de 2-D per aplicar-la a la funció:
matrix = np.arange(1, 10).reshape(3,3)

def suma_columnes_files(matrix):
    
    columnes = np.apply_along_axis(sum, 0, matrix)
    files = np.apply_along_axis(sum, 1, matrix)
    print('El total per columnes es:', columnes)
    print('El total per files es:', files)
    
suma_columnes_files(matrix)

El total per columnes es: [12 15 18]
El total per files es: [ 6 15 24]


In [ ]:
- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [21]:
import numpy as np
import matplotlib.pyplot as plt

X= np.random.randint(20,size=10)
Y= np.random.randint(20,size=10)

def f_pearson(X,Y):
    
    N = len(X)
    Pearson_corr =(N* sum(X*Y) - sum(X)*sum(Y)) / (np.sqrt(N * sum(X**2) - sum(X)**2) * np.sqrt( N * sum(Y**2) - sum(Y)**2))
    print(Pearson_corr)
    
f_pearson(X,Y)


-0.4281618983696792


In [22]:
import numpy as np
import matplotlib.pyplot as plt

x = [-2,-1,0,1,2]
y = [4,1,3,2,0]

np.corrcoef(X,Y)

array([[ 1.       , -0.4281619],
       [-0.4281619,  1.       ]])